"""NIC-IRP e-invoice table: do not use Taxable/Total as qty/rate."""
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app import (  # noqa: E402
    _nic_irp_table_ocr_is_richer,
    _ocr_suggests_gst_portal_goods_details,
    _ocr_suggests_nic_irp_einvoice_table,
    _parse_nic_irp_einvoice_qty_rate_rows,
    fix_nic_irp_einvoice_qty_rate_from_ocr,
)


NIC_IRP_OCR = """
Sr Item HSN Quantity Unit Unit Price Discount Taxable Tax Rate Other Total
No. Description Code (Rs) (Rs) Amount (GST+Cess charges (Rs)
4 DOLONEX- 300490 50 UNT 204.79 307.19 10239.5 5+0|0+0 0 10428.93
DT 20 mg 66
6 OMEZ INJ 300490 100 UNT 39.06 117.18 3906 5+0|0+0 0 3978.26
1'S 34
16 CONCOR 300490 200 UNT 110.77 664.62 22154 5+0|0+0 0 22563.85
5MG TAB 79
20 VAULT 20 300490 100 UNT 111.33 333.99 11133 5+0|0+0 0 11338.96
TAB 10's 99
21 PANTODAC 300490 54 UNT 188.41 305.22 10174.14 5+0|0+0 0 10362.36
DSR CAP's 39
22 DEXONA INJ 300439 100 UNT 8.28 24.84 828 5+0|0+0 0 843.32
2ml (20) 13
Generated By : 32AGJPP7919A1ZI
Digitally Signed by NIC-IRP
on: 18/06/2026 09:27:00
"""

JACKSON_OCR = """
JACKSON MEDICALS Inv.No. D4151 ST.THOMAS HOSPITAL
AMLOPIN 5MG TAB 10 20.32 203.20
"""

STRUCTURED_EINVOICE_OCR = """
Tax Invoice
Invoice Number : INV4567
1 30049099 - PANTODAC DSR CAP 15CAP 5 3,802.00
Quantity: 20 Unit: OTH Unit Price: 190.10
Batch: IA01656B Expiry Dt: 30/11/2027
"""


class TestNicIrpEinvoiceQtyRate(unittest.TestCase):
    def test_detects_nic_irp_not_other_formats(self):
        self.assertTrue(_ocr_suggests_nic_irp_einvoice_table(NIC_IRP_OCR))
        self.assertFalse(_ocr_suggests_gst_portal_goods_details(NIC_IRP_OCR))
        self.assertFalse(_ocr_suggests_nic_irp_einvoice_table(JACKSON_OCR))
        self.assertFalse(_ocr_suggests_nic_irp_einvoice_table(STRUCTURED_EINVOICE_OCR))

    def test_parses_vault_and_pantodac_qty_rate(self):
        rows = _parse_nic_irp_einvoice_qty_rate_rows(NIC_IRP_OCR)
        by_name = {
            re_key: r for r in rows
            for re_key in [r["product_description"].upper()]
        }
        vault = next(r for r in rows if "VAULT" in r["product_description"].upper())
        panto = next(r for r in rows if "PANTODAC" in r["product_description"].upper())
        self.assertEqual(vault["quantity"], 100)
        self.assertAlmostEqual(vault["unit_price"], 111.33, places=2)
        self.assertEqual(panto["quantity"], 54)
        self.assertAlmostEqual(panto["unit_price"], 188.41, places=2)
        self.assertTrue(by_name)

    def test_corrects_taxable_total_used_as_qty_rate(self):
        items = [
            {
                "product_description": "VAULT 20 TAB 10's",
                "hsn_code": "30049099",
                "quantity": "11133",
                "unit_price": "11338.96",
                "total_amount": "11338.96",
            },
            {
                "product_description": "PANTODAC DSR CAP's 15's",
                "hsn_code": "30049039",
                "quantity": "10174.14",
                "unit_price": "10362.36",
                "total_amount": "10362.36",
            },
            {
                "product_description": "CONCOR 5MG TAB 10'S",
                "hsn_code": "30049079",
                "quantity": "200",
                "unit_price": "110.77",
                "total_amount": "22563.85",
            },
        ]
        fixed = fix_nic_irp_einvoice_qty_rate_from_ocr(items, NIC_IRP_OCR)
        vault = next(i for i in fixed if "VAULT" in i["product_description"].upper())
        panto = next(i for i in fixed if "PANTODAC" in i["product_description"].upper())
        concor = next(i for i in fixed if "CONCOR" in i["product_description"].upper())
        self.assertEqual(str(vault["quantity"]), "100")
        self.assertEqual(vault["unit_price"], "111.33")
        self.assertEqual(str(panto["quantity"]), "54")
        self.assertEqual(panto["unit_price"], "188.41")
        self.assertEqual(str(concor["quantity"]), "200")
        self.assertEqual(concor["unit_price"], "110.77")

    def test_detects_item_table_without_signature_page(self):
        """CR-2403 pages 1-3 have the table; NIC-IRP signature is often page 4."""
        table_only = NIC_IRP_OCR.replace(
            "Digitally Signed by NIC-IRP\non: 18/06/2026 09:27:00",
            "",
        )
        table_only = (
            "1.e-Invoice Details\nDocument No. : CR-2403\n"
            "4A.Details of Goods / Services\n"
            + table_only
        )
        self.assertTrue(_ocr_suggests_nic_irp_einvoice_table(table_only))
        items = [{
            "product_description": "VAULT 20 TAB 10's",
            "hsn_code": "30049099",
            "quantity": "11133",
            "unit_price": "11338.96",
            "total_amount": "11338.96",
        }]
        fixed = fix_nic_irp_einvoice_qty_rate_from_ocr(items, table_only)
        self.assertEqual(str(fixed[0]["quantity"]), "100")
        self.assertEqual(fixed[0]["unit_price"], "111.33")

    def test_parses_pymupdf_vertical_cells_and_split_hsn(self):
        pymupdf_ocr = """
1.e-Invoice Details
Document No. : CR-2403
Sr
No.
Item
Description
HSN
Code
Quantity
Unit
Unit Price
Taxable
15
EVION LC
TAB 10's
(box**15)
300450
37
300
UNT
54.08
486.72
16224
5+0|0+0
0
16524.14
16
CONCOR
5MG TAB
10'S
300490
79
200
UNT
110.77
664.62
22154
5+0|0+0
0
22563.85
20
VAULT 20
TAB 10's
300490
99
100
UNT
111.33
333.99
11133
5+0|0+0
0
11338.96
21
PANTODAC
DSR CAP's
15's
(box**10)
300490
39
54
UNT
188.41
305.22
10174.14
5+0|0+0
0
10362.36
"""
        self.assertTrue(_ocr_suggests_nic_irp_einvoice_table(pymupdf_ocr))
        rows = _parse_nic_irp_einvoice_qty_rate_rows(pymupdf_ocr)
        vault = next(r for r in rows if "VAULT" in r["product_description"].upper())
        evion = next(r for r in rows if "EVION" in r["product_description"].upper())
        self.assertEqual(vault["quantity"], 100)
        self.assertAlmostEqual(vault["unit_price"], 111.33, places=2)
        self.assertEqual(evion["quantity"], 300)
        self.assertAlmostEqual(evion["unit_price"], 54.08, places=2)

        items = [
            {
                "product_description": "PRO EVION LC TAB",
                "quantity": "37",
                "unit_price": "16524.14",
                "total_amount": "611393.18",
            },
            {
                "product_description": "TOR XILINGIO 10/5 MG TABLETS 10'S",
                "quantity": "79",
                "unit_price": "22563.85",
                "total_amount": "1782544.15",
            },
            {
                "product_description": "VAULT 20 TAB 10TAB",
                "quantity": "11133",
                "unit_price": "11338.96",
                "total_amount": "126236641.68",
            },
            {
                "product_description": "PANTODAC DSR CAP'S 15's (box**10)",
                "quantity": "10174",
                "unit_price": "10362.36",
                "total_amount": "105428101.37",
            },
        ]
        fixed = fix_nic_irp_einvoice_qty_rate_from_ocr(items, pymupdf_ocr)
        ev = next(i for i in fixed if "EVION" in i["product_description"].upper())
        xil = next(i for i in fixed if "XILINGIO" in i["product_description"].upper())
        vt = next(i for i in fixed if "VAULT" in i["product_description"].upper())
        pt = next(i for i in fixed if "PANTODAC" in i["product_description"].upper())
        self.assertEqual(str(ev["quantity"]), "300")
        self.assertEqual(ev["unit_price"], "54.08")
        self.assertEqual(str(xil["quantity"]), "200")
        self.assertEqual(xil["unit_price"], "110.77")
        self.assertEqual(str(vt["quantity"]), "100")
        self.assertEqual(vt["unit_price"], "111.33")
        self.assertEqual(str(pt["quantity"]), "54")
        self.assertEqual(pt["unit_price"], "188.41")

    def test_keeps_plumber_table_over_garbled_tesseract(self):
        tesseract = (
            "Sr Item HSN Quantity Unit Unit Price Discount Taxable "
            "DOLONEX- 300490 10239.5 10428.93 DT 20 mg 66 "
            "VAULT 20 300490 11133 11338.96 TAB 10's 99"
        )
        self.assertTrue(_nic_irp_table_ocr_is_richer(NIC_IRP_OCR, tesseract))
        self.assertFalse(_nic_irp_table_ocr_is_richer(tesseract, NIC_IRP_OCR))
        self.assertFalse(_nic_irp_table_ocr_is_richer(JACKSON_OCR, tesseract))

    def test_does_not_touch_non_nic_items(self):
        items = [{
            "product_description": "AMLOPIN 5MG TAB",
            "quantity": "10",
            "unit_price": "20.32",
            "total_amount": "203.20",
        }]
        fixed = fix_nic_irp_einvoice_qty_rate_from_ocr(items, JACKSON_OCR)
        self.assertEqual(fixed[0]["quantity"], "10")
        self.assertEqual(fixed[0]["unit_price"], "20.32")


if __name__ == "__main__":
    unittest.main()
